# Generated by `mix boundary.ex_doc_groups`
[
  Marker: [Marker],
  "Marker.Accounts": [
    Marker.Accounts,
    Marker.Accounts.User,
    Marker.Accounts.UserNotifier,
    Marker.Accounts.UserToken
  ],
  "Marker.Library": [Marker.Library, Marker.Library.Bookmark, Marker.Library.Bookmark.Query],
  "Marker.Mailer": [Marker.Mailer],
  "Marker.Repo": [Marker.Repo],
  MarkerApp: [MarkerApp],
  MarkerWeb: [
    MarkerWeb,
    MarkerWeb.Accounts.UserAuth,
    MarkerWeb.Accounts.UserConfirmationController,
    MarkerWeb.Accounts.UserConfirmationView,
    MarkerWeb.Accounts.UserRegistrationController,
    MarkerWeb.Accounts.UserRegistrationView,
    MarkerWeb.Accounts.UserResetPasswordController,
    MarkerWeb.Accounts.UserResetPasswordView,
    MarkerWeb.Accounts.UserSessionController,
    MarkerWeb.Accounts.UserSessionView,
    MarkerWeb.Accounts.UserSettingsController,
    MarkerWeb.Accounts.UserSettingsView,
    MarkerWeb.Endpoint,
    MarkerWeb.ErrorHelpers,
    MarkerWeb.ErrorView,
    MarkerWeb.Gettext,
    MarkerWeb.LayoutView,
    MarkerWeb.PageController,
    MarkerWeb.PageView,
    MarkerWeb.Router,
    MarkerWeb.Router.Helpers,
    MarkerWeb.Telemetry
  ]
]
